-- Electromagnetics calculator definitions.

local EPSILON_0 = 8.854187817e-12
local MU_0 = 4e-7 * math.pi
local COULOMB_K = 1 / (4 * math.pi * EPSILON_0)

local function vectorInputs(prefix)
    return {{label=prefix.."x"},{label=prefix.."y"},{label=prefix.."z"}}
end

local function twoVectorInputs()
    return {{label="Ax"},{label="Ay"},{label="Az"},{label="Bx"},{label="By"},{label="Bz"}}
end

local function vectorOutputs(prefix)
    return {{label=prefix.."x"},{label=prefix.."y"},{label=prefix.."z"}}
end

local function validateNonzeroVector(v, i, name)
    if vectors.magnitude(v[i],v[i+1],v[i+2]) == 0 then return name.." cannot be the zero vector" end
end

local function requirePositive(value, name)
    if value <= 0 then return name.." must be greater than zero" end
end

function registerElectromagneticsCalculators(calculators)
    calculators.vectorMagnitude = Calculator.new({id="vectorMagnitude",title="Vector Magnitude",subtitle="Enter Cartesian components",inputs=vectorInputs("A"),outputs={{label="Magnitude"}},calculate=function(v) return vectors.magnitude(v[1],v[2],v[3]) end})
    calculators.vectorUnit = Calculator.new({id="vectorUnit",title="Unit Vector",subtitle="Find a unit vector parallel to A",inputs=vectorInputs("A"),outputs=vectorOutputs("u"),validate=function(v) return validateNonzeroVector(v,1,"A") end,calculate=function(v) return vectors.unit(v[1],v[2],v[3]) end})
    calculators.vectorDot = Calculator.new({id="vectorDot",title="Dot Product",subtitle="Calculate A dot B",inputs=twoVectorInputs(),outputs={{label="A dot B"}},calculate=function(v) return vectors.dot(v[1],v[2],v[3],v[4],v[5],v[6]) end})
    calculators.vectorCross = Calculator.new({id="vectorCross",title="Cross Product",subtitle="Calculate A x B",inputs=twoVectorInputs(),outputs={{label="Cx"},{label="Cy"},{label="Cz"},{label="Magnitude"}},calculate=function(v) local x,y,z=vectors.cross(v[1],v[2],v[3],v[4],v[5],v[6]); return x,y,z,vectors.magnitude(x,y,z) end})
    calculators.vectorAngle = Calculator.new({id="vectorAngle",title="Angle Between Vectors",subtitle="Smallest angle from A to B",inputs=twoVectorInputs(),outputs={{label="Angle",unit="degrees"}},validate=function(v) return validateNonzeroVector(v,1,"A") or validateNonzeroVector(v,4,"B") end,calculate=function(v) return vectors.angleDegrees(v[1],v[2],v[3],v[4],v[5],v[6]) end})
    calculators.vectorProjection = Calculator.new({id="vectorProjection",title="Vector Projection",subtitle="Projection of A onto B",inputs=twoVectorInputs(),outputs=vectorOutputs("P"),validate=function(v) return validateNonzeroVector(v,4,"B") end,calculate=function(v) return vectors.projection(v[1],v[2],v[3],v[4],v[5],v[6]) end})

    -- Electrostatics
    calculators.coulombsLaw = Calculator.new({id="coulombsLaw",title="Coulomb's Law",subtitle="Signed radial force; + repulsive, - attractive",inputs={{label="Charge q1",unit="C"},{label="Charge q2",unit="C"},{label="Separation r",unit="m"},{label="Relative permittivity"}},outputs={{label="Radial force",unit="N"},{label="Magnitude",unit="N"}},validate=function(v) return requirePositive(v[3],"Separation") or requirePositive(v[4],"Relative permittivity") end,calculate=function(v) local f=COULOMB_K*v[1]*v[2]/(v[4]*v[3]^2); return f,math.abs(f) end})
    calculators.pointChargeField = Calculator.new({id="pointChargeField",title="Point-Charge Electric Field",subtitle="Signed radial field from a point charge",inputs={{label="Source charge q",unit="C"},{label="Distance r",unit="m"},{label="Relative permittivity"}},outputs={{label="Radial E",unit="V/m"},{label="Magnitude",unit="V/m"}},validate=function(v) return requirePositive(v[2],"Distance") or requirePositive(v[3],"Relative permittivity") end,calculate=function(v) local e=COULOMB_K*v[1]/(v[3]*v[2]^2); return e,math.abs(e) end})
    calculators.pointChargePotential = Calculator.new({id="pointChargePotential",title="Electric Potential",subtitle="Potential due to a point charge, zero at infinity",inputs={{label="Source charge q",unit="C"},{label="Distance r",unit="m"},{label="Relative permittivity"}},outputs={{label="Potential",unit="V"}},validate=function(v) return requirePositive(v[2],"Distance") or requirePositive(v[3],"Relative permittivity") end,calculate=function(v) return COULOMB_K*v[1]/(v[3]*v[2]) end})
    calculators.forceOnCharge = Calculator.new({id="forceOnCharge",title="Force on a Charge",subtitle="Calculate F = qE in Cartesian components",inputs={{label="Charge q",unit="C"},{label="Ex",unit="V/m"},{label="Ey",unit="V/m"},{label="Ez",unit="V/m"}},outputs={{label="Fx",unit="N"},{label="Fy",unit="N"},{label="Fz",unit="N"},{label="Magnitude",unit="N"}},calculate=function(v) local x,y,z=v[1]*v[2],v[1]*v[3],v[1]*v[4]; return x,y,z,vectors.magnitude(x,y,z) end})
    calculators.gaussLaw = Calculator.new({id="gaussLaw",title="Gauss's Law",subtitle="Electric flux through a closed surface",inputs={{label="Enclosed charge",unit="C"},{label="Relative permittivity"}},outputs={{label="Electric flux",unit="V*m"}},validate=function(v) return requirePositive(v[2],"Relative permittivity") end,calculate=function(v) return v[1]/(EPSILON_0*v[2]) end})
    calculators.parallelPlateCapacitance = Calculator.new({id="parallelPlateCapacitance",title="Parallel-Plate Capacitance",subtitle="Ideal plates with uniform dielectric",inputs={{label="Plate area",unit="m^2"},{label="Plate spacing",unit="m"},{label="Relative permittivity"}},outputs={{label="Capacitance",unit="F"}},validate=function(v) return requirePositive(v[1],"Area") or requirePositive(v[2],"Spacing") or requirePositive(v[3],"Relative permittivity") end,calculate=function(v) return EPSILON_0*v[3]*v[1]/v[2] end})

    -- Magnetostatics: magnetic fields
    calculators.infiniteWireField = Calculator.new({id="infiniteWireField",title="Infinite Straight Wire",subtitle="Magnetic field at radial distance r",inputs={{label="Current I",unit="A"},{label="Distance r",unit="m"},{label="Relative permeability"}},outputs={{label="Magnetic field B",unit="T"}},validate=function(v) return requirePositive(v[2],"Distance") or requirePositive(v[3],"Relative permeability") end,calculate=function(v) return MU_0*v[3]*v[1]/(2*math.pi*v[2]) end})
    calculators.finiteWireField = Calculator.new({id="finiteWireField",title="Finite Straight Wire",subtitle="Point at perpendicular distance r",inputs={{label="Current I",unit="A"},{label="Distance r",unit="m"},{label="Angle alpha1",unit="degrees"},{label="Angle alpha2",unit="degrees"},{label="Relative permeability"}},outputs={{label="Magnetic field B",unit="T"}},validate=function(v) return requirePositive(v[2],"Distance") or requirePositive(v[5],"Relative permeability") end,calculate=function(v) return MU_0*v[5]*v[1]*(math.sin(v[3]*math.pi/180)+math.sin(v[4]*math.pi/180))/(4*math.pi*v[2]) end})
    calculators.circularLoopField = Calculator.new({id="circularLoopField",title="Circular Loop Field",subtitle="Field at center of an N-turn loop",inputs={{label="Current I",unit="A"},{label="Radius R",unit="m"},{label="Turns N"},{label="Relative permeability"}},outputs={{label="Magnetic field B",unit="T"}},validate=function(v) return requirePositive(v[2],"Radius") or requirePositive(v[3],"Turns") or requirePositive(v[4],"Relative permeability") end,calculate=function(v) return MU_0*v[4]*v[3]*v[1]/(2*v[2]) end})
    calculators.solenoidField = Calculator.new({id="solenoidField",title="Ideal Solenoid Field",subtitle="Uniform interior field B = mu NI/L",inputs={{label="Current I",unit="A"},{label="Turns N"},{label="Length L",unit="m"},{label="Relative permeability"}},outputs={{label="Magnetic field B",unit="T"}},validate=function(v) return requirePositive(v[2],"Turns") or requirePositive(v[3],"Length") or requirePositive(v[4],"Relative permeability") end,calculate=function(v) return MU_0*v[4]*v[2]*v[1]/v[3] end})
    calculators.toroidField = Calculator.new({id="toroidField",title="Ideal Toroid Field",subtitle="Field at radius r inside the core",inputs={{label="Current I",unit="A"},{label="Turns N"},{label="Radius r",unit="m"},{label="Relative permeability"}},outputs={{label="Magnetic field B",unit="T"}},validate=function(v) return requirePositive(v[2],"Turns") or requirePositive(v[3],"Radius") or requirePositive(v[4],"Relative permeability") end,calculate=function(v) return MU_0*v[4]*v[2]*v[1]/(2*math.pi*v[3]) end})

    -- Magnetostatics: forces and torque
    calculators.movingChargeMagneticForce = Calculator.new({id="movingChargeMagneticForce",title="Force on Moving Charge",subtitle="F = q(v x B)",inputs={{label="Charge q",unit="C"},{label="vx",unit="m/s"},{label="vy",unit="m/s"},{label="vz",unit="m/s"},{label="Bx",unit="T"},{label="By",unit="T"},{label="Bz",unit="T"}},outputs={{label="Fx",unit="N"},{label="Fy",unit="N"},{label="Fz",unit="N"},{label="Magnitude",unit="N"}},visibleInputCount=5,calculate=function(v) local x,y,z=vectors.cross(v[2],v[3],v[4],v[5],v[6],v[7]); x,y,z=v[1]*x,v[1]*y,v[1]*z; return x,y,z,vectors.magnitude(x,y,z) end})
    calculators.currentWireForce = Calculator.new({id="currentWireForce",title="Force on Current-Carrying Wire",subtitle="F = I(L x B)",inputs={{label="Current I",unit="A"},{label="Lx",unit="m"},{label="Ly",unit="m"},{label="Lz",unit="m"},{label="Bx",unit="T"},{label="By",unit="T"},{label="Bz",unit="T"}},outputs={{label="Fx",unit="N"},{label="Fy",unit="N"},{label="Fz",unit="N"},{label="Magnitude",unit="N"}},visibleInputCount=5,calculate=function(v) local x,y,z=vectors.cross(v[2],v[3],v[4],v[5],v[6],v[7]); x,y,z=v[1]*x,v[1]*y,v[1]*z; return x,y,z,vectors.magnitude(x,y,z) end})
    calculators.parallelWireForce = Calculator.new({id="parallelWireForce",title="Force Between Parallel Wires",subtitle="Signed F/L; + same current direction",inputs={{label="Current I1",unit="A"},{label="Current I2",unit="A"},{label="Separation d",unit="m"},{label="Relative permeability"}},outputs={{label="Force per length",unit="N/m"},{label="Magnitude",unit="N/m"}},validate=function(v) return requirePositive(v[3],"Separation") or requirePositive(v[4],"Relative permeability") end,calculate=function(v) local f=MU_0*v[4]*v[1]*v[2]/(2*math.pi*v[3]); return f,math.abs(f) end})
    calculators.currentLoopTorque = Calculator.new({id="currentLoopTorque",title="Torque on Current Loop",subtitle="Magnitude tau = NIAB sin(theta)",inputs={{label="Turns N"},{label="Current I",unit="A"},{label="Loop area A",unit="m^2"},{label="Magnetic field B",unit="T"},{label="Angle theta",unit="degrees"}},outputs={{label="Torque",unit="N*m"},{label="Magnetic moment",unit="A*m^2"}},validate=function(v) return requirePositive(v[1],"Turns") or requirePositive(v[3],"Area") or requirePositive(v[4],"Magnetic field") end,calculate=function(v) local m=v[1]*v[2]*v[3]; return m*v[4]*math.sin(v[5]*math.pi/180),m end})

    -- Flux, induction, and inductance
    calculators.magneticFlux = Calculator.new({id="magneticFlux",title="Magnetic Flux",subtitle="Uniform field through a flat surface",inputs={{label="Magnetic field B",unit="T"},{label="Area A",unit="m^2"},{label="Angle theta",unit="degrees"}},outputs={{label="Magnetic flux",unit="Wb"}},validate=function(v) return requirePositive(v[2],"Area") end,calculate=function(v) return v[1]*v[2]*math.cos(v[3]*math.pi/180) end})
    calculators.faradayLaw = Calculator.new({id="faradayLaw",title="Faraday's Law",subtitle="Average induced EMF = -N DeltaPhi/Delta t",inputs={{label="Turns N"},{label="Initial flux",unit="Wb"},{label="Final flux",unit="Wb"},{label="Time interval",unit="s"}},outputs={{label="Induced EMF",unit="V"},{label="Magnitude",unit="V"}},validate=function(v) return requirePositive(v[1],"Turns") or requirePositive(v[4],"Time interval") end,calculate=function(v) local e=-v[1]*(v[3]-v[2])/v[4]; return e,math.abs(e) end})
    calculators.solenoidInductance = Calculator.new({id="solenoidInductance",title="Solenoid Inductance",subtitle="Ideal L = mu N^2 A / length",inputs={{label="Turns N"},{label="Area A",unit="m^2"},{label="Length",unit="m"},{label="Relative permeability"}},outputs={{label="Inductance",unit="H"}},validate=function(v) return requirePositive(v[1],"Turns") or requirePositive(v[2],"Area") or requirePositive(v[3],"Length") or requirePositive(v[4],"Relative permeability") end,calculate=function(v) return MU_0*v[4]*v[1]^2*v[2]/v[3] end})
    calculators.mutualInductance = Calculator.new({id="mutualInductance",title="Mutual Inductance",subtitle="M = k sqrt(L1 L2)",inputs={{label="Inductance L1",unit="H"},{label="Inductance L2",unit="H"},{label="Coupling coefficient k"}},outputs={{label="Mutual inductance",unit="H"}},validate=function(v) if v[1] <= 0 or v[2] <= 0 then return "Inductances must be greater than zero" end; if v[3] < 0 or v[3] > 1 then return "Coupling coefficient must be from 0 to 1" end end,calculate=function(v) return v[3]*math.sqrt(v[1]*v[2]) end})
    calculators.inductorEnergy = Calculator.new({id="inductorEnergy",title="Energy Stored in Inductor",subtitle="W = 1/2 L I^2",inputs={{label="Inductance L",unit="H"},{label="Current I",unit="A"}},outputs={{label="Stored energy",unit="J"}},validate=function(v) return requirePositive(v[1],"Inductance") end,calculate=function(v) return 0.5*v[1]*v[2]^2 end})
end
