-- Formula Solver definitions built with the shared Formula framework.

function registerFormulaSolvers(calculators)
    calculators.formulaOhm = Formula.calculator({id="formulaOhm",title="Ohm's Law",equation="V = I R",variables={{label="Voltage V",unit="V"},{label="Current I",unit="A"},{label="Resistance R",unit="ohm"}},validate=function(v,m) return Formula.requireNonzero(v,2,"Current",m) or Formula.requireNonzero(v,3,"Resistance",m) end,solve=function(v,m) if m==1 then return v[2]*v[3] elseif m==2 then return v[1]/v[3] else return v[1]/v[2] end end})
    calculators.formulaPower = Formula.calculator({id="formulaPower",title="Electrical Power",equation="P = V I",variables={{label="Power P",unit="W"},{label="Voltage V",unit="V"},{label="Current I",unit="A"}},validate=function(v,m) return Formula.requireNonzero(v,2,"Voltage",m) or Formula.requireNonzero(v,3,"Current",m) end,solve=function(v,m) if m==1 then return v[2]*v[3] elseif m==2 then return v[1]/v[3] else return v[1]/v[2] end end})
    calculators.formulaForce = Formula.calculator({id="formulaForce",title="Newton's Second Law",equation="F = m a",variables={{label="Force F",unit="N"},{label="Mass m",unit="kg"},{label="Acceleration a",unit="m/s^2"}},validate=function(v,m) return Formula.requireNonzero(v,2,"Mass",m) or Formula.requireNonzero(v,3,"Acceleration",m) end,solve=function(v,m) if m==1 then return v[2]*v[3] elseif m==2 then return v[1]/v[3] else return v[1]/v[2] end end})
    calculators.formulaDensity = Formula.calculator({id="formulaDensity",title="Density",equation="rho = m / V",variables={{label="Density rho",unit="kg/m^3"},{label="Mass m",unit="kg"},{label="Volume V",unit="m^3"}},validate=function(v,m) return Formula.requirePositive(v,3,"Volume",m) or Formula.requirePositive(v,1,"Density",m) end,solve=function(v,m) if m==1 then return v[2]/v[3] elseif m==2 then return v[1]*v[3] else return v[2]/v[1] end end})
    calculators.formulaPressure = Formula.calculator({id="formulaPressure",title="Pressure",equation="p = F / A",variables={{label="Pressure p",unit="Pa"},{label="Force F",unit="N"},{label="Area A",unit="m^2"}},validate=function(v,m) return Formula.requirePositive(v,3,"Area",m) or Formula.requireNonzero(v,1,"Pressure",m) end,solve=function(v,m) if m==1 then return v[2]/v[3] elseif m==2 then return v[1]*v[3] else return v[2]/v[1] end end})
    calculators.formulaStress = Formula.calculator({id="formulaStress",title="Normal Stress",equation="sigma = F / A",variables={{label="Stress sigma",unit="Pa"},{label="Force F",unit="N"},{label="Area A",unit="m^2"}},validate=function(v,m) return Formula.requirePositive(v,3,"Area",m) or Formula.requireNonzero(v,1,"Stress",m) end,solve=function(v,m) if m==1 then return v[2]/v[3] elseif m==2 then return v[1]*v[3] else return v[2]/v[1] end end})
    calculators.formulaIdealGas = Formula.calculator({id="formulaIdealGas",title="Ideal Gas Law",equation="P V = n R T",variables={{label="Pressure P",unit="Pa"},{label="Volume V",unit="m^3"},{label="Amount n",unit="mol"},{label="Gas constant R",unit="J/(mol K)"},{label="Temperature T",unit="K"}},validate=function(v,m) for i,name in ipairs({"Pressure","Volume","Amount","Gas constant","Temperature"}) do local e=Formula.requirePositive(v,i,name,m); if e then return e end end end,solve=function(v,m) if m==1 then return v[3]*v[4]*v[5]/v[2] elseif m==2 then return v[3]*v[4]*v[5]/v[1] elseif m==3 then return v[1]*v[2]/(v[4]*v[5]) elseif m==4 then return v[1]*v[2]/(v[3]*v[5]) else return v[1]*v[2]/(v[3]*v[4]) end end})
    calculators.formulaWave = Formula.calculator({id="formulaWave",title="Wave Relation",equation="v = f lambda",variables={{label="Wave speed v",unit="m/s"},{label="Frequency f",unit="Hz"},{label="Wavelength lambda",unit="m"}},validate=function(v,m) return Formula.requirePositive(v,1,"Wave speed",m) or Formula.requirePositive(v,2,"Frequency",m) or Formula.requirePositive(v,3,"Wavelength",m) end,solve=function(v,m) if m==1 then return v[2]*v[3] elseif m==2 then return v[1]/v[3] else return v[1]/v[2] end end})
    calculators.formulaHeat = Formula.calculator({id="formulaHeat",title="Sensible Heat",equation="Q = m c DeltaT",variables={{label="Heat Q",unit="J"},{label="Mass m",unit="kg"},{label="Specific heat c",unit="J/(kg K)"},{label="Temperature change",unit="K"}},validate=function(v,m) return Formula.requireNonzero(v,2,"Mass",m) or Formula.requireNonzero(v,3,"Specific heat",m) or Formula.requireNonzero(v,4,"Temperature change",m) end,solve=function(v,m) if m==1 then return v[2]*v[3]*v[4] elseif m==2 then return v[1]/(v[3]*v[4]) elseif m==3 then return v[1]/(v[2]*v[4]) else return v[1]/(v[2]*v[3]) end end})
end
